'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace PaymentLine
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PaymentLines_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/paymentlines")>  _
    Partial Public Class PaymentLines_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ReadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadByRecIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsUpdatedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRecIdFromKeyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.H2HIntegration.My.MySettings.Default.H2HIntegration_PaymentLine_PaymentLines_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ReadCompleted As ReadCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadByRecIdCompleted As ReadByRecIdCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadMultipleCompleted As ReadMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event IsUpdatedCompleted As IsUpdatedCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRecIdFromKeyCompleted As GetRecIdFromKeyCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateCompleted As CreateCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateMultipleCompleted As CreateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCompleted As UpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateMultipleCompleted As UpdateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCompleted As DeleteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal Line_No As Integer, ByVal Type As String) As <System.Xml.Serialization.XmlElementAttribute("PaymentLines")> PaymentLines
            Dim results() As Object = Me.Invoke("Read", New Object() {Line_No, Type})
            Return CType(results(0),PaymentLines)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal Line_No As Integer, ByVal Type As String)
            Me.ReadAsync(Line_No, Type, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal Line_No As Integer, ByVal Type As String, ByVal userState As Object)
            If (Me.ReadOperationCompleted Is Nothing) Then
                Me.ReadOperationCompleted = AddressOf Me.OnReadOperationCompleted
            End If
            Me.InvokeAsync("Read", New Object() {Line_No, Type}, Me.ReadOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadCompleted(Me, New ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("PaymentLines")> PaymentLines
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),PaymentLines)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String)
            Me.ReadByRecIdAsync(recId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String, ByVal userState As Object)
            If (Me.ReadByRecIdOperationCompleted Is Nothing) Then
                Me.ReadByRecIdOperationCompleted = AddressOf Me.OnReadByRecIdOperationCompleted
            End If
            Me.InvokeAsync("ReadByRecId", New Object() {recId}, Me.ReadByRecIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadByRecIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadByRecIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadByRecIdCompleted(Me, New ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As PaymentLines_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> PaymentLines()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),PaymentLines())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As PaymentLines_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer)
            Me.ReadMultipleAsync(filter, bookmarkKey, setSize, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As PaymentLines_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal userState As Object)
            If (Me.ReadMultipleOperationCompleted Is Nothing) Then
                Me.ReadMultipleOperationCompleted = AddressOf Me.OnReadMultipleOperationCompleted
            End If
            Me.InvokeAsync("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, Me.ReadMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadMultipleCompleted(Me, New ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String)
            Me.IsUpdatedAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.IsUpdatedOperationCompleted Is Nothing) Then
                Me.IsUpdatedOperationCompleted = AddressOf Me.OnIsUpdatedOperationCompleted
            End If
            Me.InvokeAsync("IsUpdated", New Object() {Key}, Me.IsUpdatedOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsUpdatedOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsUpdatedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsUpdatedCompleted(Me, New IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String)
            Me.GetRecIdFromKeyAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.GetRecIdFromKeyOperationCompleted Is Nothing) Then
                Me.GetRecIdFromKeyOperationCompleted = AddressOf Me.OnGetRecIdFromKeyOperationCompleted
            End If
            Me.InvokeAsync("GetRecIdFromKey", New Object() {Key}, Me.GetRecIdFromKeyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRecIdFromKeyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRecIdFromKeyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRecIdFromKeyCompleted(Me, New GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:Create", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="Create_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Create(ByRef PaymentLines As PaymentLines)
            Dim results() As Object = Me.Invoke("Create", New Object() {PaymentLines})
            PaymentLines = CType(results(0),PaymentLines)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal PaymentLines As PaymentLines)
            Me.CreateAsync(PaymentLines, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal PaymentLines As PaymentLines, ByVal userState As Object)
            If (Me.CreateOperationCompleted Is Nothing) Then
                Me.CreateOperationCompleted = AddressOf Me.OnCreateOperationCompleted
            End If
            Me.InvokeAsync("Create", New Object() {PaymentLines}, Me.CreateOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCompleted(Me, New CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:CreateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="CreateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef PaymentLines_List() As PaymentLines)
            Dim results() As Object = Me.Invoke("CreateMultiple", New Object() {PaymentLines_List})
            PaymentLines_List = CType(results(0),PaymentLines())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal PaymentLines_List() As PaymentLines)
            Me.CreateMultipleAsync(PaymentLines_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal PaymentLines_List() As PaymentLines, ByVal userState As Object)
            If (Me.CreateMultipleOperationCompleted Is Nothing) Then
                Me.CreateMultipleOperationCompleted = AddressOf Me.OnCreateMultipleOperationCompleted
            End If
            Me.InvokeAsync("CreateMultiple", New Object() {PaymentLines_List}, Me.CreateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateMultipleCompleted(Me, New CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef PaymentLines As PaymentLines)
            Dim results() As Object = Me.Invoke("Update", New Object() {PaymentLines})
            PaymentLines = CType(results(0),PaymentLines)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal PaymentLines As PaymentLines)
            Me.UpdateAsync(PaymentLines, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal PaymentLines As PaymentLines, ByVal userState As Object)
            If (Me.UpdateOperationCompleted Is Nothing) Then
                Me.UpdateOperationCompleted = AddressOf Me.OnUpdateOperationCompleted
            End If
            Me.InvokeAsync("Update", New Object() {PaymentLines}, Me.UpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCompleted(Me, New UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef PaymentLines_List() As PaymentLines)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {PaymentLines_List})
            PaymentLines_List = CType(results(0),PaymentLines())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal PaymentLines_List() As PaymentLines)
            Me.UpdateMultipleAsync(PaymentLines_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal PaymentLines_List() As PaymentLines, ByVal userState As Object)
            If (Me.UpdateMultipleOperationCompleted Is Nothing) Then
                Me.UpdateMultipleOperationCompleted = AddressOf Me.OnUpdateMultipleOperationCompleted
            End If
            Me.InvokeAsync("UpdateMultiple", New Object() {PaymentLines_List}, Me.UpdateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateMultipleCompleted(Me, New UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentlines:Delete", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", ResponseElementName:="Delete_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentlines", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String)
            Me.DeleteAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.DeleteOperationCompleted Is Nothing) Then
                Me.DeleteOperationCompleted = AddressOf Me.OnDeleteOperationCompleted
            End If
            Me.InvokeAsync("Delete", New Object() {Key}, Me.DeleteOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCompleted(Me, New DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentlines")>  _
    Partial Public Class PaymentLines
        
        Private keyField As String
        
        Private typeField As String
        
        Private account_NoField As String
        
        Private account_NameField As String
        
        Private payment_NarrationField As String
        
        Private global_Dimension_1_CodeField As String
        
        Private shortcut_Dimension_2_CodeField As String
        
        Private shortcut_Dimension_3_CodeField As String
        
        Private shortcut_Dimension_4_CodeField As String
        
        Private advert_CodeField As String
        
        Private amountField As Decimal
        
        Private amountFieldSpecified As Boolean
        
        Private withholding_Tax_CodeField As String
        
        Private withholding_Tax_AmountField As Decimal
        
        Private withholding_Tax_AmountFieldSpecified As Boolean
        
        Private net_AmountField As Decimal
        
        Private net_AmountFieldSpecified As Boolean
        
        Private vAT_Prod_Posting_GroupField As String
        
        Private netAmount_LCYField As Decimal
        
        Private netAmount_LCYFieldSpecified As Boolean
        
        Private vendor_Bank_AccountField As String
        
        Private payee_Account_TypeField As Payee_Account_Type
        
        Private payee_Account_TypeFieldSpecified As Boolean
        
        Private payee_Account_NoField As String
        
        Private payee_NoField As String
        
        Private payeeField As String
        
        Private payee_Bank_Account_NoField As String
        
        Private cheque_NoField As String
        
        Private bankField As String
        
        Private security_NoField As String
        
        Private payee_Email_AddressField As String
        
        Private apply_to_Account_TypeField As Apply_to_Account_Type
        
        Private apply_to_Account_TypeFieldSpecified As Boolean
        
        Private applies_to_Doc_TypeField As Applies_to_Doc_Type
        
        Private applies_to_Doc_TypeFieldSpecified As Boolean
        
        Private applies_to_Doc_NoField As String
        
        Private applies_to_IDField As String
        
        Private currency_CodeField As String
        
        Private transaction_IDField As String
        
        Private pFAField As String
        
        Private pFA_PeriodField As String
        
        Private num_Alloc_InterestField As Decimal
        
        Private num_Alloc_InterestFieldSpecified As Boolean
        
        Private num_Recon_InterestField As Decimal
        
        Private num_Recon_InterestFieldSpecified As Boolean
        
        Private h2H_StatusField As H2H_Status
        
        Private h2H_StatusFieldSpecified As Boolean
        
        Private line_NoField As Integer
        
        Private line_NoFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Account_No() As String
            Get
                Return Me.account_NoField
            End Get
            Set
                Me.account_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Account_Name() As String
            Get
                Return Me.account_NameField
            End Get
            Set
                Me.account_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payment_Narration() As String
            Get
                Return Me.payment_NarrationField
            End Get
            Set
                Me.payment_NarrationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Global_Dimension_1_Code() As String
            Get
                Return Me.global_Dimension_1_CodeField
            End Get
            Set
                Me.global_Dimension_1_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_2_Code() As String
            Get
                Return Me.shortcut_Dimension_2_CodeField
            End Get
            Set
                Me.shortcut_Dimension_2_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_3_Code() As String
            Get
                Return Me.shortcut_Dimension_3_CodeField
            End Get
            Set
                Me.shortcut_Dimension_3_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_4_Code() As String
            Get
                Return Me.shortcut_Dimension_4_CodeField
            End Get
            Set
                Me.shortcut_Dimension_4_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Advert_Code() As String
            Get
                Return Me.advert_CodeField
            End Get
            Set
                Me.advert_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AmountSpecified() As Boolean
            Get
                Return Me.amountFieldSpecified
            End Get
            Set
                Me.amountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Withholding_Tax_Code() As String
            Get
                Return Me.withholding_Tax_CodeField
            End Get
            Set
                Me.withholding_Tax_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Withholding_Tax_Amount() As Decimal
            Get
                Return Me.withholding_Tax_AmountField
            End Get
            Set
                Me.withholding_Tax_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Withholding_Tax_AmountSpecified() As Boolean
            Get
                Return Me.withholding_Tax_AmountFieldSpecified
            End Get
            Set
                Me.withholding_Tax_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Net_Amount() As Decimal
            Get
                Return Me.net_AmountField
            End Get
            Set
                Me.net_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Net_AmountSpecified() As Boolean
            Get
                Return Me.net_AmountFieldSpecified
            End Get
            Set
                Me.net_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VAT_Prod_Posting_Group() As String
            Get
                Return Me.vAT_Prod_Posting_GroupField
            End Get
            Set
                Me.vAT_Prod_Posting_GroupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NetAmount_LCY() As Decimal
            Get
                Return Me.netAmount_LCYField
            End Get
            Set
                Me.netAmount_LCYField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NetAmount_LCYSpecified() As Boolean
            Get
                Return Me.netAmount_LCYFieldSpecified
            End Get
            Set
                Me.netAmount_LCYFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Vendor_Bank_Account() As String
            Get
                Return Me.vendor_Bank_AccountField
            End Get
            Set
                Me.vendor_Bank_AccountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_Account_Type() As Payee_Account_Type
            Get
                Return Me.payee_Account_TypeField
            End Get
            Set
                Me.payee_Account_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Payee_Account_TypeSpecified() As Boolean
            Get
                Return Me.payee_Account_TypeFieldSpecified
            End Get
            Set
                Me.payee_Account_TypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_Account_No() As String
            Get
                Return Me.payee_Account_NoField
            End Get
            Set
                Me.payee_Account_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_No() As String
            Get
                Return Me.payee_NoField
            End Get
            Set
                Me.payee_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee() As String
            Get
                Return Me.payeeField
            End Get
            Set
                Me.payeeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_Bank_Account_No() As String
            Get
                Return Me.payee_Bank_Account_NoField
            End Get
            Set
                Me.payee_Bank_Account_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("<Cheque_No>")>  _
        Public Property Cheque_No() As String
            Get
                Return Me.cheque_NoField
            End Get
            Set
                Me.cheque_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank() As String
            Get
                Return Me.bankField
            End Get
            Set
                Me.bankField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Security_No() As String
            Get
                Return Me.security_NoField
            End Get
            Set
                Me.security_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_Email_Address() As String
            Get
                Return Me.payee_Email_AddressField
            End Get
            Set
                Me.payee_Email_AddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Apply_to_Account_Type() As Apply_to_Account_Type
            Get
                Return Me.apply_to_Account_TypeField
            End Get
            Set
                Me.apply_to_Account_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Apply_to_Account_TypeSpecified() As Boolean
            Get
                Return Me.apply_to_Account_TypeFieldSpecified
            End Get
            Set
                Me.apply_to_Account_TypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Applies_to_Doc_Type() As Applies_to_Doc_Type
            Get
                Return Me.applies_to_Doc_TypeField
            End Get
            Set
                Me.applies_to_Doc_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Applies_to_Doc_TypeSpecified() As Boolean
            Get
                Return Me.applies_to_Doc_TypeFieldSpecified
            End Get
            Set
                Me.applies_to_Doc_TypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Applies_to_Doc_No() As String
            Get
                Return Me.applies_to_Doc_NoField
            End Get
            Set
                Me.applies_to_Doc_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Applies_to_ID() As String
            Get
                Return Me.applies_to_IDField
            End Get
            Set
                Me.applies_to_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Currency_Code() As String
            Get
                Return Me.currency_CodeField
            End Get
            Set
                Me.currency_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaction_ID() As String
            Get
                Return Me.transaction_IDField
            End Get
            Set
                Me.transaction_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PFA() As String
            Get
                Return Me.pFAField
            End Get
            Set
                Me.pFAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PFA_Period() As String
            Get
                Return Me.pFA_PeriodField
            End Get
            Set
                Me.pFA_PeriodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Num_Alloc_Interest() As Decimal
            Get
                Return Me.num_Alloc_InterestField
            End Get
            Set
                Me.num_Alloc_InterestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Num_Alloc_InterestSpecified() As Boolean
            Get
                Return Me.num_Alloc_InterestFieldSpecified
            End Get
            Set
                Me.num_Alloc_InterestFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Num_Recon_Interest() As Decimal
            Get
                Return Me.num_Recon_InterestField
            End Get
            Set
                Me.num_Recon_InterestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Num_Recon_InterestSpecified() As Boolean
            Get
                Return Me.num_Recon_InterestFieldSpecified
            End Get
            Set
                Me.num_Recon_InterestFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property H2H_Status() As H2H_Status
            Get
                Return Me.h2H_StatusField
            End Get
            Set
                Me.h2H_StatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property H2H_StatusSpecified() As Boolean
            Get
                Return Me.h2H_StatusFieldSpecified
            End Get
            Set
                Me.h2H_StatusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Line_No() As Integer
            Get
                Return Me.line_NoField
            End Get
            Set
                Me.line_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Line_NoSpecified() As Boolean
            Get
                Return Me.line_NoFieldSpecified
            End Get
            Set
                Me.line_NoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentlines")>  _
    Public Enum Payee_Account_Type
        
        '''<remarks/>
        Customer
        
        '''<remarks/>
        Vendor
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentlines")>  _
    Public Enum Apply_to_Account_Type
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Customer
        
        '''<remarks/>
        Vendor
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentlines")>  _
    Public Enum Applies_to_Doc_Type
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Payment
        
        '''<remarks/>
        Invoice
        
        '''<remarks/>
        Credit_Memo
        
        '''<remarks/>
        Finance_Charge_Memo
        
        '''<remarks/>
        Reminder
        
        '''<remarks/>
        Refund
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentlines")>  _
    Public Enum H2H_Status
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Dispatched
        
        '''<remarks/>
        Successful
        
        '''<remarks/>
        Failed
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentlines")>  _
    Partial Public Class PaymentLines_Filter
        
        Private fieldField As PaymentLines_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As PaymentLines_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentlines")>  _
    Public Enum PaymentLines_Fields
        
        '''<remarks/>
        Type
        
        '''<remarks/>
        Account_No
        
        '''<remarks/>
        Account_Name
        
        '''<remarks/>
        Payment_Narration
        
        '''<remarks/>
        Global_Dimension_1_Code
        
        '''<remarks/>
        Shortcut_Dimension_2_Code
        
        '''<remarks/>
        Shortcut_Dimension_3_Code
        
        '''<remarks/>
        Shortcut_Dimension_4_Code
        
        '''<remarks/>
        Advert_Code
        
        '''<remarks/>
        Amount
        
        '''<remarks/>
        Withholding_Tax_Code
        
        '''<remarks/>
        Withholding_Tax_Amount
        
        '''<remarks/>
        Net_Amount
        
        '''<remarks/>
        VAT_Prod_Posting_Group
        
        '''<remarks/>
        NetAmount_LCY
        
        '''<remarks/>
        Vendor_Bank_Account
        
        '''<remarks/>
        Payee_Account_Type
        
        '''<remarks/>
        Payee_Account_No
        
        '''<remarks/>
        Payee_No
        
        '''<remarks/>
        Payee
        
        '''<remarks/>
        Payee_Bank_Account_No
        
        '''<remarks/>
        _x003C_Cheque_No_x003E_
        
        '''<remarks/>
        Bank
        
        '''<remarks/>
        Security_No
        
        '''<remarks/>
        Payee_Email_Address
        
        '''<remarks/>
        Apply_to_Account_Type
        
        '''<remarks/>
        Applies_to_Doc_Type
        
        '''<remarks/>
        Applies_to_Doc_No
        
        '''<remarks/>
        Applies_to_ID
        
        '''<remarks/>
        Currency_Code
        
        '''<remarks/>
        Transaction_ID
        
        '''<remarks/>
        PFA
        
        '''<remarks/>
        PFA_Period
        
        '''<remarks/>
        Num_Alloc_Interest
        
        '''<remarks/>
        Num_Recon_Interest
        
        '''<remarks/>
        H2H_Status
        
        '''<remarks/>
        Line_No
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub ReadCompletedEventHandler(ByVal sender As Object, ByVal e As ReadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PaymentLines
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentLines)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub ReadByRecIdCompletedEventHandler(ByVal sender As Object, ByVal e As ReadByRecIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadByRecIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PaymentLines
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentLines)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub ReadMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As ReadMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PaymentLines()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentLines())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub IsUpdatedCompletedEventHandler(ByVal sender As Object, ByVal e As IsUpdatedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsUpdatedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub GetRecIdFromKeyCompletedEventHandler(ByVal sender As Object, ByVal e As GetRecIdFromKeyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRecIdFromKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub CreateCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property PaymentLines() As PaymentLines
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentLines)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub CreateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As CreateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property PaymentLines_List() As PaymentLines()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentLines())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub UpdateCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property PaymentLines() As PaymentLines
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentLines)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub UpdateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property PaymentLines_List() As PaymentLines()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentLines())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DeleteCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
