'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace BankList
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="BeneficiaryBankList_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist")>  _
    Partial Public Class BeneficiaryBankList_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ReadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadByRecIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsUpdatedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRecIdFromKeyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private CreateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private DeleteOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.H2HIntegration.My.MySettings.Default.H2HIntegration_BankList_BeneficiaryBankList_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ReadCompleted As ReadCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadByRecIdCompleted As ReadByRecIdCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadMultipleCompleted As ReadMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event IsUpdatedCompleted As IsUpdatedCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRecIdFromKeyCompleted As GetRecIdFromKeyCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateCompleted As CreateCompletedEventHandler
        
        '''<remarks/>
        Public Event CreateMultipleCompleted As CreateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCompleted As UpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateMultipleCompleted As UpdateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event DeleteCompleted As DeleteCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal Code As String, ByVal Bank_Name As String) As <System.Xml.Serialization.XmlElementAttribute("BeneficiaryBankList")> BeneficiaryBankList
            Dim results() As Object = Me.Invoke("Read", New Object() {Code, Bank_Name})
            Return CType(results(0),BeneficiaryBankList)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal Code As String, ByVal Bank_Name As String)
            Me.ReadAsync(Code, Bank_Name, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal Code As String, ByVal Bank_Name As String, ByVal userState As Object)
            If (Me.ReadOperationCompleted Is Nothing) Then
                Me.ReadOperationCompleted = AddressOf Me.OnReadOperationCompleted
            End If
            Me.InvokeAsync("Read", New Object() {Code, Bank_Name}, Me.ReadOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadCompleted(Me, New ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("BeneficiaryBankList")> BeneficiaryBankList
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),BeneficiaryBankList)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String)
            Me.ReadByRecIdAsync(recId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String, ByVal userState As Object)
            If (Me.ReadByRecIdOperationCompleted Is Nothing) Then
                Me.ReadByRecIdOperationCompleted = AddressOf Me.OnReadByRecIdOperationCompleted
            End If
            Me.InvokeAsync("ReadByRecId", New Object() {recId}, Me.ReadByRecIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadByRecIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadByRecIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadByRecIdCompleted(Me, New ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As BeneficiaryBankList_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> BeneficiaryBankList()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),BeneficiaryBankList())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As BeneficiaryBankList_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer)
            Me.ReadMultipleAsync(filter, bookmarkKey, setSize, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As BeneficiaryBankList_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal userState As Object)
            If (Me.ReadMultipleOperationCompleted Is Nothing) Then
                Me.ReadMultipleOperationCompleted = AddressOf Me.OnReadMultipleOperationCompleted
            End If
            Me.InvokeAsync("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, Me.ReadMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadMultipleCompleted(Me, New ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String)
            Me.IsUpdatedAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.IsUpdatedOperationCompleted Is Nothing) Then
                Me.IsUpdatedOperationCompleted = AddressOf Me.OnIsUpdatedOperationCompleted
            End If
            Me.InvokeAsync("IsUpdated", New Object() {Key}, Me.IsUpdatedOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsUpdatedOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsUpdatedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsUpdatedCompleted(Me, New IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String)
            Me.GetRecIdFromKeyAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.GetRecIdFromKeyOperationCompleted Is Nothing) Then
                Me.GetRecIdFromKeyOperationCompleted = AddressOf Me.OnGetRecIdFromKeyOperationCompleted
            End If
            Me.InvokeAsync("GetRecIdFromKey", New Object() {Key}, Me.GetRecIdFromKeyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRecIdFromKeyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRecIdFromKeyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRecIdFromKeyCompleted(Me, New GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:Create", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="Create_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Create(ByRef BeneficiaryBankList As BeneficiaryBankList)
            Dim results() As Object = Me.Invoke("Create", New Object() {BeneficiaryBankList})
            BeneficiaryBankList = CType(results(0),BeneficiaryBankList)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal BeneficiaryBankList As BeneficiaryBankList)
            Me.CreateAsync(BeneficiaryBankList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateAsync(ByVal BeneficiaryBankList As BeneficiaryBankList, ByVal userState As Object)
            If (Me.CreateOperationCompleted Is Nothing) Then
                Me.CreateOperationCompleted = AddressOf Me.OnCreateOperationCompleted
            End If
            Me.InvokeAsync("Create", New Object() {BeneficiaryBankList}, Me.CreateOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateCompleted(Me, New CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:CreateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="CreateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub CreateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef BeneficiaryBankList_List() As BeneficiaryBankList)
            Dim results() As Object = Me.Invoke("CreateMultiple", New Object() {BeneficiaryBankList_List})
            BeneficiaryBankList_List = CType(results(0),BeneficiaryBankList())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal BeneficiaryBankList_List() As BeneficiaryBankList)
            Me.CreateMultipleAsync(BeneficiaryBankList_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub CreateMultipleAsync(ByVal BeneficiaryBankList_List() As BeneficiaryBankList, ByVal userState As Object)
            If (Me.CreateMultipleOperationCompleted Is Nothing) Then
                Me.CreateMultipleOperationCompleted = AddressOf Me.OnCreateMultipleOperationCompleted
            End If
            Me.InvokeAsync("CreateMultiple", New Object() {BeneficiaryBankList_List}, Me.CreateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnCreateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.CreateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent CreateMultipleCompleted(Me, New CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef BeneficiaryBankList As BeneficiaryBankList)
            Dim results() As Object = Me.Invoke("Update", New Object() {BeneficiaryBankList})
            BeneficiaryBankList = CType(results(0),BeneficiaryBankList)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal BeneficiaryBankList As BeneficiaryBankList)
            Me.UpdateAsync(BeneficiaryBankList, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal BeneficiaryBankList As BeneficiaryBankList, ByVal userState As Object)
            If (Me.UpdateOperationCompleted Is Nothing) Then
                Me.UpdateOperationCompleted = AddressOf Me.OnUpdateOperationCompleted
            End If
            Me.InvokeAsync("Update", New Object() {BeneficiaryBankList}, Me.UpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCompleted(Me, New UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef BeneficiaryBankList_List() As BeneficiaryBankList)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {BeneficiaryBankList_List})
            BeneficiaryBankList_List = CType(results(0),BeneficiaryBankList())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal BeneficiaryBankList_List() As BeneficiaryBankList)
            Me.UpdateMultipleAsync(BeneficiaryBankList_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal BeneficiaryBankList_List() As BeneficiaryBankList, ByVal userState As Object)
            If (Me.UpdateMultipleOperationCompleted Is Nothing) Then
                Me.UpdateMultipleOperationCompleted = AddressOf Me.OnUpdateMultipleOperationCompleted
            End If
            Me.InvokeAsync("UpdateMultiple", New Object() {BeneficiaryBankList_List}, Me.UpdateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateMultipleCompleted(Me, New UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/beneficiarybanklist:Delete", RequestNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", ResponseElementName:="Delete_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String)
            Me.DeleteAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub DeleteAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.DeleteOperationCompleted Is Nothing) Then
                Me.DeleteOperationCompleted = AddressOf Me.OnDeleteOperationCompleted
            End If
            Me.InvokeAsync("Delete", New Object() {Key}, Me.DeleteOperationCompleted, userState)
        End Sub
        
        Private Sub OnDeleteOperationCompleted(ByVal arg As Object)
            If (Not (Me.DeleteCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent DeleteCompleted(Me, New DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist")>  _
    Partial Public Class BeneficiaryBankList
        
        Private keyField As String
        
        Private codeField As String
        
        Private bank_CodeField As String
        
        Private branch_CodeField As String
        
        Private bank_NameField As String
        
        Private sWIFT_CODEField As String
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Code() As String
            Get
                Return Me.codeField
            End Get
            Set
                Me.codeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank_Code() As String
            Get
                Return Me.bank_CodeField
            End Get
            Set
                Me.bank_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Branch_Code() As String
            Get
                Return Me.branch_CodeField
            End Get
            Set
                Me.branch_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank_Name() As String
            Get
                Return Me.bank_NameField
            End Get
            Set
                Me.bank_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SWIFT_CODE() As String
            Get
                Return Me.sWIFT_CODEField
            End Get
            Set
                Me.sWIFT_CODEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist")>  _
    Partial Public Class BeneficiaryBankList_Filter
        
        Private fieldField As BeneficiaryBankList_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As BeneficiaryBankList_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/beneficiarybanklist")>  _
    Public Enum BeneficiaryBankList_Fields
        
        '''<remarks/>
        Code
        
        '''<remarks/>
        Bank_Code
        
        '''<remarks/>
        Branch_Code
        
        '''<remarks/>
        Bank_Name
        
        '''<remarks/>
        SWIFT_CODE
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub ReadCompletedEventHandler(ByVal sender As Object, ByVal e As ReadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BeneficiaryBankList
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BeneficiaryBankList)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub ReadByRecIdCompletedEventHandler(ByVal sender As Object, ByVal e As ReadByRecIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadByRecIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BeneficiaryBankList
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BeneficiaryBankList)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub ReadMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As ReadMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As BeneficiaryBankList()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BeneficiaryBankList())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub IsUpdatedCompletedEventHandler(ByVal sender As Object, ByVal e As IsUpdatedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsUpdatedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub GetRecIdFromKeyCompletedEventHandler(ByVal sender As Object, ByVal e As GetRecIdFromKeyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRecIdFromKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub CreateCompletedEventHandler(ByVal sender As Object, ByVal e As CreateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property BeneficiaryBankList() As BeneficiaryBankList
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BeneficiaryBankList)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub CreateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As CreateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class CreateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property BeneficiaryBankList_List() As BeneficiaryBankList()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BeneficiaryBankList())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub UpdateCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property BeneficiaryBankList() As BeneficiaryBankList
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BeneficiaryBankList)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub UpdateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property BeneficiaryBankList_List() As BeneficiaryBankList()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),BeneficiaryBankList())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub DeleteCompletedEventHandler(ByVal sender As Object, ByVal e As DeleteCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class DeleteCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
