'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace PaymentVoucherCard
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PaymentVoucherCard_Binding", [Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Partial Public Class PaymentVoucherCard_Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ReadOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadByRecIdOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ReadMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private IsUpdatedOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GetRecIdFromKeyOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UpdateMultipleOperationCompleted As System.Threading.SendOrPostCallback
        
        Private Delete_PVLinesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.H2HIntegration.My.MySettings.Default.H2HIntegration_PaymentVoucherCard_PaymentVoucherCard_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ReadCompleted As ReadCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadByRecIdCompleted As ReadByRecIdCompletedEventHandler
        
        '''<remarks/>
        Public Event ReadMultipleCompleted As ReadMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event IsUpdatedCompleted As IsUpdatedCompletedEventHandler
        
        '''<remarks/>
        Public Event GetRecIdFromKeyCompleted As GetRecIdFromKeyCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateCompleted As UpdateCompletedEventHandler
        
        '''<remarks/>
        Public Event UpdateMultipleCompleted As UpdateMultipleCompletedEventHandler
        
        '''<remarks/>
        Public Event Delete_PVLinesCompleted As Delete_PVLinesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentvouchercard:Read", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", ResponseElementName:="Read_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Read(ByVal No As String) As <System.Xml.Serialization.XmlElementAttribute("PaymentVoucherCard")> PaymentVoucherCard
            Dim results() As Object = Me.Invoke("Read", New Object() {No})
            Return CType(results(0),PaymentVoucherCard)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal No As String)
            Me.ReadAsync(No, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadAsync(ByVal No As String, ByVal userState As Object)
            If (Me.ReadOperationCompleted Is Nothing) Then
                Me.ReadOperationCompleted = AddressOf Me.OnReadOperationCompleted
            End If
            Me.InvokeAsync("Read", New Object() {No}, Me.ReadOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadCompleted(Me, New ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentvouchercard:ReadByRecId", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", ResponseElementName:="ReadByRecId_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadByRecId(ByVal recId As String) As <System.Xml.Serialization.XmlElementAttribute("PaymentVoucherCard")> PaymentVoucherCard
            Dim results() As Object = Me.Invoke("ReadByRecId", New Object() {recId})
            Return CType(results(0),PaymentVoucherCard)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String)
            Me.ReadByRecIdAsync(recId, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadByRecIdAsync(ByVal recId As String, ByVal userState As Object)
            If (Me.ReadByRecIdOperationCompleted Is Nothing) Then
                Me.ReadByRecIdOperationCompleted = AddressOf Me.OnReadByRecIdOperationCompleted
            End If
            Me.InvokeAsync("ReadByRecId", New Object() {recId}, Me.ReadByRecIdOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadByRecIdOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadByRecIdCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadByRecIdCompleted(Me, New ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentvouchercard:ReadMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", ResponseElementName:="ReadMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ReadMultiple(<System.Xml.Serialization.XmlElementAttribute("filter")> ByVal filter() As PaymentVoucherCard_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer) As <System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result"), System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> PaymentVoucherCard()
            Dim results() As Object = Me.Invoke("ReadMultiple", New Object() {filter, bookmarkKey, setSize})
            Return CType(results(0),PaymentVoucherCard())
        End Function
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As PaymentVoucherCard_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer)
            Me.ReadMultipleAsync(filter, bookmarkKey, setSize, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ReadMultipleAsync(ByVal filter() As PaymentVoucherCard_Filter, ByVal bookmarkKey As String, ByVal setSize As Integer, ByVal userState As Object)
            If (Me.ReadMultipleOperationCompleted Is Nothing) Then
                Me.ReadMultipleOperationCompleted = AddressOf Me.OnReadMultipleOperationCompleted
            End If
            Me.InvokeAsync("ReadMultiple", New Object() {filter, bookmarkKey, setSize}, Me.ReadMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnReadMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.ReadMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ReadMultipleCompleted(Me, New ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentvouchercard:IsUpdated", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", ResponseElementName:="IsUpdated_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function IsUpdated(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")> Boolean
            Dim results() As Object = Me.Invoke("IsUpdated", New Object() {Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String)
            Me.IsUpdatedAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub IsUpdatedAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.IsUpdatedOperationCompleted Is Nothing) Then
                Me.IsUpdatedOperationCompleted = AddressOf Me.OnIsUpdatedOperationCompleted
            End If
            Me.InvokeAsync("IsUpdated", New Object() {Key}, Me.IsUpdatedOperationCompleted, userState)
        End Sub
        
        Private Sub OnIsUpdatedOperationCompleted(ByVal arg As Object)
            If (Not (Me.IsUpdatedCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent IsUpdatedCompleted(Me, New IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentvouchercard:GetRecIdFromKey", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", ResponseElementName:="GetRecIdFromKey_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GetRecIdFromKey(ByVal Key As String) As <System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")> String
            Dim results() As Object = Me.Invoke("GetRecIdFromKey", New Object() {Key})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String)
            Me.GetRecIdFromKeyAsync(Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetRecIdFromKeyAsync(ByVal Key As String, ByVal userState As Object)
            If (Me.GetRecIdFromKeyOperationCompleted Is Nothing) Then
                Me.GetRecIdFromKeyOperationCompleted = AddressOf Me.OnGetRecIdFromKeyOperationCompleted
            End If
            Me.InvokeAsync("GetRecIdFromKey", New Object() {Key}, Me.GetRecIdFromKeyOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetRecIdFromKeyOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetRecIdFromKeyCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetRecIdFromKeyCompleted(Me, New GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentvouchercard:Update", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", ResponseElementName:="Update_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub Update(ByRef PaymentVoucherCard As PaymentVoucherCard)
            Dim results() As Object = Me.Invoke("Update", New Object() {PaymentVoucherCard})
            PaymentVoucherCard = CType(results(0),PaymentVoucherCard)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal PaymentVoucherCard As PaymentVoucherCard)
            Me.UpdateAsync(PaymentVoucherCard, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateAsync(ByVal PaymentVoucherCard As PaymentVoucherCard, ByVal userState As Object)
            If (Me.UpdateOperationCompleted Is Nothing) Then
                Me.UpdateOperationCompleted = AddressOf Me.OnUpdateOperationCompleted
            End If
            Me.InvokeAsync("Update", New Object() {PaymentVoucherCard}, Me.UpdateOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateCompleted(Me, New UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentvouchercard:UpdateMultiple", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", ResponseElementName:="UpdateMultiple_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub UpdateMultiple(<System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)> ByRef PaymentVoucherCard_List() As PaymentVoucherCard)
            Dim results() As Object = Me.Invoke("UpdateMultiple", New Object() {PaymentVoucherCard_List})
            PaymentVoucherCard_List = CType(results(0),PaymentVoucherCard())
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal PaymentVoucherCard_List() As PaymentVoucherCard)
            Me.UpdateMultipleAsync(PaymentVoucherCard_List, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UpdateMultipleAsync(ByVal PaymentVoucherCard_List() As PaymentVoucherCard, ByVal userState As Object)
            If (Me.UpdateMultipleOperationCompleted Is Nothing) Then
                Me.UpdateMultipleOperationCompleted = AddressOf Me.OnUpdateMultipleOperationCompleted
            End If
            Me.InvokeAsync("UpdateMultiple", New Object() {PaymentVoucherCard_List}, Me.UpdateMultipleOperationCompleted, userState)
        End Sub
        
        Private Sub OnUpdateMultipleOperationCompleted(ByVal arg As Object)
            If (Not (Me.UpdateMultipleCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UpdateMultipleCompleted(Me, New UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/paymentvouchercard:Delete_PVLines", RequestNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", ResponseElementName:="Delete_PVLines_Result", ResponseNamespace:="urn:microsoft-dynamics-schemas/page/paymentvouchercard", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function Delete_PVLines(ByVal PVLines_Key As String) As <System.Xml.Serialization.XmlElementAttribute("Delete_PVLines_Result")> Boolean
            Dim results() As Object = Me.Invoke("Delete_PVLines", New Object() {PVLines_Key})
            Return CType(results(0),Boolean)
        End Function
        
        '''<remarks/>
        Public Overloads Sub Delete_PVLinesAsync(ByVal PVLines_Key As String)
            Me.Delete_PVLinesAsync(PVLines_Key, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub Delete_PVLinesAsync(ByVal PVLines_Key As String, ByVal userState As Object)
            If (Me.Delete_PVLinesOperationCompleted Is Nothing) Then
                Me.Delete_PVLinesOperationCompleted = AddressOf Me.OnDelete_PVLinesOperationCompleted
            End If
            Me.InvokeAsync("Delete_PVLines", New Object() {PVLines_Key}, Me.Delete_PVLinesOperationCompleted, userState)
        End Sub
        
        Private Sub OnDelete_PVLinesOperationCompleted(ByVal arg As Object)
            If (Not (Me.Delete_PVLinesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent Delete_PVLinesCompleted(Me, New Delete_PVLinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Partial Public Class PaymentVoucherCard
        
        Private keyField As String
        
        Private noField As String
        
        Private dateField As Date
        
        Private dateFieldSpecified As Boolean
        
        Private global_Dimension_1_CodeField As String
        
        Private function_NameField As String
        
        Private shortcut_Dimension_2_CodeField As String
        
        Private budget_Center_NameField As String
        
        Private shortcut_Dimension_3_CodeField As String
        
        Private dim3Field As String
        
        Private shortcut_Dimension_4_CodeField As String
        
        Private dim4Field As String
        
        Private pay_ModeField As Pay_Mode
        
        Private pay_ModeFieldSpecified As Boolean
        
        Private bank_TransferField As Boolean
        
        Private bank_TransferFieldSpecified As Boolean
        
        Private currency_CodeField As String
        
        Private paying_Bank_AccountField As String
        
        Private bank_NameField As String
        
        Private payeeField As String
        
        Private payee_Account_NumberField As String
        
        Private on_Behalf_OfField As String
        
        Private payment_NarrationField As String
        
        Private invoice_Currency_CodeField As String
        
        Private cheque_TypeField As Cheque_Type
        
        Private cheque_TypeFieldSpecified As Boolean
        
        Private lPO_CheckField As Boolean
        
        Private lPO_CheckFieldSpecified As Boolean
        
        Private statusField As Status
        
        Private statusFieldSpecified As Boolean
        
        Private cashierField As String
        
        Private total_Payment_AmountField As Decimal
        
        Private total_Payment_AmountFieldSpecified As Boolean
        
        Private total_VAT_AmountField As Decimal
        
        Private total_VAT_AmountFieldSpecified As Boolean
        
        Private total_Witholding_Tax_AmountField As Decimal
        
        Private total_Witholding_Tax_AmountFieldSpecified As Boolean
        
        Private total_Retention_AmountField As Decimal
        
        Private total_Retention_AmountFieldSpecified As Boolean
        
        Private _Total_Payment_Amount_Total_Witholding_Tax_Amount__Total_VAT_Amount__Total_Retention_AmountField As Decimal
        
        Private _Total_Payment_Amount_Total_Witholding_Tax_Amount__Total_VAT_Amount__Total_Retention_AmountFieldSpecified As Boolean
        
        Private total_Payment_Amount_LCYField As Decimal
        
        Private total_Payment_Amount_LCYFieldSpecified As Boolean
        
        Private cheque_NumberField As String
        
        Private payment_Release_DateField As Date
        
        Private payment_Release_DateFieldSpecified As Boolean
        
        Private responsibility_CenterField As String
        
        Private payment_Request_NoField As String
        
        Private posted_Bank_ImprestField As String
        
        Private h2H_StatusField As H2H_Status
        
        Private h2H_StatusFieldSpecified As Boolean
        
        Private pVLinesField() As Payment_Lines
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property No() As String
            Get
                Return Me.noField
            End Get
            Set
                Me.noField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property [Date]() As Date
            Get
                Return Me.dateField
            End Get
            Set
                Me.dateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property DateSpecified() As Boolean
            Get
                Return Me.dateFieldSpecified
            End Get
            Set
                Me.dateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Global_Dimension_1_Code() As String
            Get
                Return Me.global_Dimension_1_CodeField
            End Get
            Set
                Me.global_Dimension_1_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Function_Name() As String
            Get
                Return Me.function_NameField
            End Get
            Set
                Me.function_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_2_Code() As String
            Get
                Return Me.shortcut_Dimension_2_CodeField
            End Get
            Set
                Me.shortcut_Dimension_2_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Budget_Center_Name() As String
            Get
                Return Me.budget_Center_NameField
            End Get
            Set
                Me.budget_Center_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_3_Code() As String
            Get
                Return Me.shortcut_Dimension_3_CodeField
            End Get
            Set
                Me.shortcut_Dimension_3_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Dim3() As String
            Get
                Return Me.dim3Field
            End Get
            Set
                Me.dim3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_4_Code() As String
            Get
                Return Me.shortcut_Dimension_4_CodeField
            End Get
            Set
                Me.shortcut_Dimension_4_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Dim4() As String
            Get
                Return Me.dim4Field
            End Get
            Set
                Me.dim4Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Pay_Mode() As Pay_Mode
            Get
                Return Me.pay_ModeField
            End Get
            Set
                Me.pay_ModeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Pay_ModeSpecified() As Boolean
            Get
                Return Me.pay_ModeFieldSpecified
            End Get
            Set
                Me.pay_ModeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank_Transfer() As Boolean
            Get
                Return Me.bank_TransferField
            End Get
            Set
                Me.bank_TransferField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Bank_TransferSpecified() As Boolean
            Get
                Return Me.bank_TransferFieldSpecified
            End Get
            Set
                Me.bank_TransferFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Currency_Code() As String
            Get
                Return Me.currency_CodeField
            End Get
            Set
                Me.currency_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Paying_Bank_Account() As String
            Get
                Return Me.paying_Bank_AccountField
            End Get
            Set
                Me.paying_Bank_AccountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank_Name() As String
            Get
                Return Me.bank_NameField
            End Get
            Set
                Me.bank_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee() As String
            Get
                Return Me.payeeField
            End Get
            Set
                Me.payeeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_Account_Number() As String
            Get
                Return Me.payee_Account_NumberField
            End Get
            Set
                Me.payee_Account_NumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property On_Behalf_Of() As String
            Get
                Return Me.on_Behalf_OfField
            End Get
            Set
                Me.on_Behalf_OfField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payment_Narration() As String
            Get
                Return Me.payment_NarrationField
            End Get
            Set
                Me.payment_NarrationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Invoice_Currency_Code() As String
            Get
                Return Me.invoice_Currency_CodeField
            End Get
            Set
                Me.invoice_Currency_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cheque_Type() As Cheque_Type
            Get
                Return Me.cheque_TypeField
            End Get
            Set
                Me.cheque_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Cheque_TypeSpecified() As Boolean
            Get
                Return Me.cheque_TypeFieldSpecified
            End Get
            Set
                Me.cheque_TypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property LPO_Check() As Boolean
            Get
                Return Me.lPO_CheckField
            End Get
            Set
                Me.lPO_CheckField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property LPO_CheckSpecified() As Boolean
            Get
                Return Me.lPO_CheckFieldSpecified
            End Get
            Set
                Me.lPO_CheckFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Status() As Status
            Get
                Return Me.statusField
            End Get
            Set
                Me.statusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property StatusSpecified() As Boolean
            Get
                Return Me.statusFieldSpecified
            End Get
            Set
                Me.statusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Cashier() As String
            Get
                Return Me.cashierField
            End Get
            Set
                Me.cashierField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total_Payment_Amount() As Decimal
            Get
                Return Me.total_Payment_AmountField
            End Get
            Set
                Me.total_Payment_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Total_Payment_AmountSpecified() As Boolean
            Get
                Return Me.total_Payment_AmountFieldSpecified
            End Get
            Set
                Me.total_Payment_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total_VAT_Amount() As Decimal
            Get
                Return Me.total_VAT_AmountField
            End Get
            Set
                Me.total_VAT_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Total_VAT_AmountSpecified() As Boolean
            Get
                Return Me.total_VAT_AmountFieldSpecified
            End Get
            Set
                Me.total_VAT_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total_Witholding_Tax_Amount() As Decimal
            Get
                Return Me.total_Witholding_Tax_AmountField
            End Get
            Set
                Me.total_Witholding_Tax_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Total_Witholding_Tax_AmountSpecified() As Boolean
            Get
                Return Me.total_Witholding_Tax_AmountFieldSpecified
            End Get
            Set
                Me.total_Witholding_Tax_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total_Retention_Amount() As Decimal
            Get
                Return Me.total_Retention_AmountField
            End Get
            Set
                Me.total_Retention_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Total_Retention_AmountSpecified() As Boolean
            Get
                Return Me.total_Retention_AmountFieldSpecified
            End Get
            Set
                Me.total_Retention_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("_Total_Payment_Amount_Total_Witholding_Tax_Amount_+_Total_VAT_Amount_+_Total_Rete"& _ 
            "ntion_Amount")>  _
        Public Property _Total_Payment_Amount_Total_Witholding_Tax_Amount__Total_VAT_Amount__Total_Retention_Amount() As Decimal
            Get
                Return Me._Total_Payment_Amount_Total_Witholding_Tax_Amount__Total_VAT_Amount__Total_Retention_AmountField
            End Get
            Set
                Me._Total_Payment_Amount_Total_Witholding_Tax_Amount__Total_VAT_Amount__Total_Retention_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property _Total_Payment_Amount_Total_Witholding_Tax_Amount__Total_VAT_Amount__Total_Retention_AmountSpecified() As Boolean
            Get
                Return Me._Total_Payment_Amount_Total_Witholding_Tax_Amount__Total_VAT_Amount__Total_Retention_AmountFieldSpecified
            End Get
            Set
                Me._Total_Payment_Amount_Total_Witholding_Tax_Amount__Total_VAT_Amount__Total_Retention_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Total_Payment_Amount_LCY() As Decimal
            Get
                Return Me.total_Payment_Amount_LCYField
            End Get
            Set
                Me.total_Payment_Amount_LCYField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Total_Payment_Amount_LCYSpecified() As Boolean
            Get
                Return Me.total_Payment_Amount_LCYFieldSpecified
            End Get
            Set
                Me.total_Payment_Amount_LCYFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("<Cheque_Number>")>  _
        Public Property Cheque_Number() As String
            Get
                Return Me.cheque_NumberField
            End Get
            Set
                Me.cheque_NumberField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date")>  _
        Public Property Payment_Release_Date() As Date
            Get
                Return Me.payment_Release_DateField
            End Get
            Set
                Me.payment_Release_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Payment_Release_DateSpecified() As Boolean
            Get
                Return Me.payment_Release_DateFieldSpecified
            End Get
            Set
                Me.payment_Release_DateFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Responsibility_Center() As String
            Get
                Return Me.responsibility_CenterField
            End Get
            Set
                Me.responsibility_CenterField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payment_Request_No() As String
            Get
                Return Me.payment_Request_NoField
            End Get
            Set
                Me.payment_Request_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Posted_Bank_Imprest() As String
            Get
                Return Me.posted_Bank_ImprestField
            End Get
            Set
                Me.posted_Bank_ImprestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property H2H_Status() As H2H_Status
            Get
                Return Me.h2H_StatusField
            End Get
            Set
                Me.h2H_StatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property H2H_StatusSpecified() As Boolean
            Get
                Return Me.h2H_StatusFieldSpecified
            End Get
            Set
                Me.h2H_StatusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute(IsNullable:=false)>  _
        Public Property PVLines() As Payment_Lines()
            Get
                Return Me.pVLinesField
            End Get
            Set
                Me.pVLinesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Public Enum Pay_Mode
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Cash
        
        '''<remarks/>
        Cheque
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Public Enum Cheque_Type
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Computer_Check
        
        '''<remarks/>
        Manual_Check
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Public Enum Status
        
        '''<remarks/>
        Pending
        
        '''<remarks/>
        _x0031_st_Approval
        
        '''<remarks/>
        _x0032_nd_Approval
        
        '''<remarks/>
        Cheque_Printing
        
        '''<remarks/>
        Posted
        
        '''<remarks/>
        Cancelled
        
        '''<remarks/>
        Checking
        
        '''<remarks/>
        Rejected
        
        '''<remarks/>
        Pending_Approval
        
        '''<remarks/>
        Approved
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Public Enum H2H_Status
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Dispatched
        
        '''<remarks/>
        Successful
        
        '''<remarks/>
        Failed
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Partial Public Class Payment_Lines
        
        Private keyField As String
        
        Private typeField As String
        
        Private account_NoField As String
        
        Private account_NameField As String
        
        Private payment_NarrationField As String
        
        Private global_Dimension_1_CodeField As String
        
        Private shortcut_Dimension_2_CodeField As String
        
        Private shortcut_Dimension_3_CodeField As String
        
        Private shortcut_Dimension_4_CodeField As String
        
        Private advert_CodeField As String
        
        Private amountField As Decimal
        
        Private amountFieldSpecified As Boolean
        
        Private withholding_Tax_CodeField As String
        
        Private withholding_Tax_AmountField As Decimal
        
        Private withholding_Tax_AmountFieldSpecified As Boolean
        
        Private net_AmountField As Decimal
        
        Private net_AmountFieldSpecified As Boolean
        
        Private vAT_Prod_Posting_GroupField As String
        
        Private netAmount_LCYField As Decimal
        
        Private netAmount_LCYFieldSpecified As Boolean
        
        Private vendor_Bank_AccountField As String
        
        Private payee_Account_TypeField As Payee_Account_Type
        
        Private payee_Account_TypeFieldSpecified As Boolean
        
        Private payee_Account_NoField As String
        
        Private payee_NoField As String
        
        Private payeeField As String
        
        Private payee_Bank_Account_NoField As String
        
        Private cheque_NoField As String
        
        Private bankField As String
        
        Private security_NoField As String
        
        Private payee_Email_AddressField As String
        
        Private apply_to_Account_TypeField As Apply_to_Account_Type
        
        Private apply_to_Account_TypeFieldSpecified As Boolean
        
        Private applies_to_Doc_TypeField As Applies_to_Doc_Type
        
        Private applies_to_Doc_TypeFieldSpecified As Boolean
        
        Private applies_to_Doc_NoField As String
        
        Private applies_to_IDField As String
        
        Private currency_CodeField As String
        
        Private transaction_IDField As String
        
        Private pFAField As String
        
        Private pFA_PeriodField As String
        
        Private num_Alloc_InterestField As Decimal
        
        Private num_Alloc_InterestFieldSpecified As Boolean
        
        Private num_Recon_InterestField As Decimal
        
        Private num_Recon_InterestFieldSpecified As Boolean
        
        Private h2H_StatusField As H2H_Status_56023
        
        Private h2H_StatusFieldSpecified As Boolean
        
        Private line_NoField As Integer
        
        Private line_NoFieldSpecified As Boolean
        
        '''<remarks/>
        Public Property Key() As String
            Get
                Return Me.keyField
            End Get
            Set
                Me.keyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Type() As String
            Get
                Return Me.typeField
            End Get
            Set
                Me.typeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Account_No() As String
            Get
                Return Me.account_NoField
            End Get
            Set
                Me.account_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Account_Name() As String
            Get
                Return Me.account_NameField
            End Get
            Set
                Me.account_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payment_Narration() As String
            Get
                Return Me.payment_NarrationField
            End Get
            Set
                Me.payment_NarrationField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Global_Dimension_1_Code() As String
            Get
                Return Me.global_Dimension_1_CodeField
            End Get
            Set
                Me.global_Dimension_1_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_2_Code() As String
            Get
                Return Me.shortcut_Dimension_2_CodeField
            End Get
            Set
                Me.shortcut_Dimension_2_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_3_Code() As String
            Get
                Return Me.shortcut_Dimension_3_CodeField
            End Get
            Set
                Me.shortcut_Dimension_3_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Shortcut_Dimension_4_Code() As String
            Get
                Return Me.shortcut_Dimension_4_CodeField
            End Get
            Set
                Me.shortcut_Dimension_4_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Advert_Code() As String
            Get
                Return Me.advert_CodeField
            End Get
            Set
                Me.advert_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Amount() As Decimal
            Get
                Return Me.amountField
            End Get
            Set
                Me.amountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property AmountSpecified() As Boolean
            Get
                Return Me.amountFieldSpecified
            End Get
            Set
                Me.amountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Withholding_Tax_Code() As String
            Get
                Return Me.withholding_Tax_CodeField
            End Get
            Set
                Me.withholding_Tax_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Withholding_Tax_Amount() As Decimal
            Get
                Return Me.withholding_Tax_AmountField
            End Get
            Set
                Me.withholding_Tax_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Withholding_Tax_AmountSpecified() As Boolean
            Get
                Return Me.withholding_Tax_AmountFieldSpecified
            End Get
            Set
                Me.withholding_Tax_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Net_Amount() As Decimal
            Get
                Return Me.net_AmountField
            End Get
            Set
                Me.net_AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Net_AmountSpecified() As Boolean
            Get
                Return Me.net_AmountFieldSpecified
            End Get
            Set
                Me.net_AmountFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VAT_Prod_Posting_Group() As String
            Get
                Return Me.vAT_Prod_Posting_GroupField
            End Get
            Set
                Me.vAT_Prod_Posting_GroupField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property NetAmount_LCY() As Decimal
            Get
                Return Me.netAmount_LCYField
            End Get
            Set
                Me.netAmount_LCYField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property NetAmount_LCYSpecified() As Boolean
            Get
                Return Me.netAmount_LCYFieldSpecified
            End Get
            Set
                Me.netAmount_LCYFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Vendor_Bank_Account() As String
            Get
                Return Me.vendor_Bank_AccountField
            End Get
            Set
                Me.vendor_Bank_AccountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_Account_Type() As Payee_Account_Type
            Get
                Return Me.payee_Account_TypeField
            End Get
            Set
                Me.payee_Account_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Payee_Account_TypeSpecified() As Boolean
            Get
                Return Me.payee_Account_TypeFieldSpecified
            End Get
            Set
                Me.payee_Account_TypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_Account_No() As String
            Get
                Return Me.payee_Account_NoField
            End Get
            Set
                Me.payee_Account_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_No() As String
            Get
                Return Me.payee_NoField
            End Get
            Set
                Me.payee_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee() As String
            Get
                Return Me.payeeField
            End Get
            Set
                Me.payeeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_Bank_Account_No() As String
            Get
                Return Me.payee_Bank_Account_NoField
            End Get
            Set
                Me.payee_Bank_Account_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("<Cheque_No>")>  _
        Public Property Cheque_No() As String
            Get
                Return Me.cheque_NoField
            End Get
            Set
                Me.cheque_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank() As String
            Get
                Return Me.bankField
            End Get
            Set
                Me.bankField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Security_No() As String
            Get
                Return Me.security_NoField
            End Get
            Set
                Me.security_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Payee_Email_Address() As String
            Get
                Return Me.payee_Email_AddressField
            End Get
            Set
                Me.payee_Email_AddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Apply_to_Account_Type() As Apply_to_Account_Type
            Get
                Return Me.apply_to_Account_TypeField
            End Get
            Set
                Me.apply_to_Account_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Apply_to_Account_TypeSpecified() As Boolean
            Get
                Return Me.apply_to_Account_TypeFieldSpecified
            End Get
            Set
                Me.apply_to_Account_TypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Applies_to_Doc_Type() As Applies_to_Doc_Type
            Get
                Return Me.applies_to_Doc_TypeField
            End Get
            Set
                Me.applies_to_Doc_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Applies_to_Doc_TypeSpecified() As Boolean
            Get
                Return Me.applies_to_Doc_TypeFieldSpecified
            End Get
            Set
                Me.applies_to_Doc_TypeFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Applies_to_Doc_No() As String
            Get
                Return Me.applies_to_Doc_NoField
            End Get
            Set
                Me.applies_to_Doc_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Applies_to_ID() As String
            Get
                Return Me.applies_to_IDField
            End Get
            Set
                Me.applies_to_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Currency_Code() As String
            Get
                Return Me.currency_CodeField
            End Get
            Set
                Me.currency_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaction_ID() As String
            Get
                Return Me.transaction_IDField
            End Get
            Set
                Me.transaction_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PFA() As String
            Get
                Return Me.pFAField
            End Get
            Set
                Me.pFAField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PFA_Period() As String
            Get
                Return Me.pFA_PeriodField
            End Get
            Set
                Me.pFA_PeriodField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Num_Alloc_Interest() As Decimal
            Get
                Return Me.num_Alloc_InterestField
            End Get
            Set
                Me.num_Alloc_InterestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Num_Alloc_InterestSpecified() As Boolean
            Get
                Return Me.num_Alloc_InterestFieldSpecified
            End Get
            Set
                Me.num_Alloc_InterestFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Num_Recon_Interest() As Decimal
            Get
                Return Me.num_Recon_InterestField
            End Get
            Set
                Me.num_Recon_InterestField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Num_Recon_InterestSpecified() As Boolean
            Get
                Return Me.num_Recon_InterestFieldSpecified
            End Get
            Set
                Me.num_Recon_InterestFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property H2H_Status() As H2H_Status_56023
            Get
                Return Me.h2H_StatusField
            End Get
            Set
                Me.h2H_StatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property H2H_StatusSpecified() As Boolean
            Get
                Return Me.h2H_StatusFieldSpecified
            End Get
            Set
                Me.h2H_StatusFieldSpecified = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Line_No() As Integer
            Get
                Return Me.line_NoField
            End Get
            Set
                Me.line_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property Line_NoSpecified() As Boolean
            Get
                Return Me.line_NoFieldSpecified
            End Get
            Set
                Me.line_NoFieldSpecified = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Public Enum Payee_Account_Type
        
        '''<remarks/>
        Customer
        
        '''<remarks/>
        Vendor
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Public Enum Apply_to_Account_Type
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Customer
        
        '''<remarks/>
        Vendor
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Public Enum Applies_to_Doc_Type
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Payment
        
        '''<remarks/>
        Invoice
        
        '''<remarks/>
        Credit_Memo
        
        '''<remarks/>
        Finance_Charge_Memo
        
        '''<remarks/>
        Reminder
        
        '''<remarks/>
        Refund
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Public Enum H2H_Status_56023
        
        '''<remarks/>
        _blank_
        
        '''<remarks/>
        Dispatched
        
        '''<remarks/>
        Successful
        
        '''<remarks/>
        Failed
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Partial Public Class PaymentVoucherCard_Filter
        
        Private fieldField As PaymentVoucherCard_Fields
        
        Private criteriaField As String
        
        '''<remarks/>
        Public Property Field() As PaymentVoucherCard_Fields
            Get
                Return Me.fieldField
            End Get
            Set
                Me.fieldField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Criteria() As String
            Get
                Return Me.criteriaField
            End Get
            Set
                Me.criteriaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:microsoft-dynamics-schemas/page/paymentvouchercard")>  _
    Public Enum PaymentVoucherCard_Fields
        
        '''<remarks/>
        No
        
        '''<remarks/>
        [Date]
        
        '''<remarks/>
        Global_Dimension_1_Code
        
        '''<remarks/>
        Function_Name
        
        '''<remarks/>
        Shortcut_Dimension_2_Code
        
        '''<remarks/>
        Budget_Center_Name
        
        '''<remarks/>
        Shortcut_Dimension_3_Code
        
        '''<remarks/>
        Dim3
        
        '''<remarks/>
        Shortcut_Dimension_4_Code
        
        '''<remarks/>
        Dim4
        
        '''<remarks/>
        Pay_Mode
        
        '''<remarks/>
        Bank_Transfer
        
        '''<remarks/>
        Currency_Code
        
        '''<remarks/>
        Paying_Bank_Account
        
        '''<remarks/>
        Bank_Name
        
        '''<remarks/>
        Payee
        
        '''<remarks/>
        Payee_Account_Number
        
        '''<remarks/>
        On_Behalf_Of
        
        '''<remarks/>
        Payment_Narration
        
        '''<remarks/>
        Invoice_Currency_Code
        
        '''<remarks/>
        Cheque_Type
        
        '''<remarks/>
        LPO_Check
        
        '''<remarks/>
        Status
        
        '''<remarks/>
        Cashier
        
        '''<remarks/>
        Total_Payment_Amount
        
        '''<remarks/>
        Total_VAT_Amount
        
        '''<remarks/>
        Total_Witholding_Tax_Amount
        
        '''<remarks/>
        Total_Retention_Amount
        
        '''<remarks/>
        _Total_Payment_Amount_Total_Witholding_Tax_Amount__x002B__Total_VAT_Amount__x002B__Total_Retention_Amount
        
        '''<remarks/>
        Total_Payment_Amount_LCY
        
        '''<remarks/>
        _x003C_Cheque_Number_x003E_
        
        '''<remarks/>
        Payment_Release_Date
        
        '''<remarks/>
        Responsibility_Center
        
        '''<remarks/>
        Payment_Request_No
        
        '''<remarks/>
        Posted_Bank_Imprest
        
        '''<remarks/>
        H2H_Status
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub ReadCompletedEventHandler(ByVal sender As Object, ByVal e As ReadCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PaymentVoucherCard
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentVoucherCard)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub ReadByRecIdCompletedEventHandler(ByVal sender As Object, ByVal e As ReadByRecIdCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadByRecIdCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PaymentVoucherCard
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentVoucherCard)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub ReadMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As ReadMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ReadMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As PaymentVoucherCard()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentVoucherCard())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub IsUpdatedCompletedEventHandler(ByVal sender As Object, ByVal e As IsUpdatedCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class IsUpdatedCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub GetRecIdFromKeyCompletedEventHandler(ByVal sender As Object, ByVal e As GetRecIdFromKeyCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetRecIdFromKeyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub UpdateCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property PaymentVoucherCard() As PaymentVoucherCard
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentVoucherCard)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub UpdateMultipleCompletedEventHandler(ByVal sender As Object, ByVal e As UpdateMultipleCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UpdateMultipleCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property PaymentVoucherCard_List() As PaymentVoucherCard()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),PaymentVoucherCard())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")>  _
    Public Delegate Sub Delete_PVLinesCompletedEventHandler(ByVal sender As Object, ByVal e As Delete_PVLinesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class Delete_PVLinesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Boolean
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Boolean)
            End Get
        End Property
    End Class
End Namespace
